name: Docus Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docus Deploy
      uses: peter-evans/docus-action@v2.0.0
      with:
        build-command: |
          cd docs
          docus build
        deploy-token: ${{ secrets.DEPLOY_TOKEN }}
        deploy-repository: KaanaOfficial/AppBase
